// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NiceBody","status":true,"description":"Show the nice body of our character and her beautiful clothes.","parameters":{"ORDER":"nakedbody|v[50]|express,back|v[51]|express,front|Body|Head","ACTOR_ID":"1","EXPRESS_PREFIX":"exp_"}}
];
