// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NiceBody","status":true,"description":"Show the nice body of our character and her beautiful clothes.","parameters":{"ORDER":"nakedbody|v[50]|express,back|v[51]|express,front|Body|Head","ACTOR_ID":"1","EXPRESS_PREFIX":"exp_"}},
{"name":"SkipPartyCommand","status":true,"description":"skip the command choose fight or escape on battle.","parameters":{}},
{"name":"BattleUIAdjustment","status":true,"description":"Adjust the Battle UI positions.","parameters":{}},
{"name":"MessageEx","status":true,"description":"","parameters":{}},
{"name":"CraftSystem","status":true,"description":"","parameters":{}},
{"name":"RandomMap","status":true,"description":"Generate Map randomly.","parameters":{}},
{"name":"InventoryLimitation","status":true,"description":"Make player's inventory has limit size.","parameters":{}},
{"name":"GainItemHint","status":true,"description":"Add a hint when you get item.","parameters":{"gainItemHint":"获得了","loseItemHint":"失去了","boxHint":"道具箱：%NUM%","hintWindowDurations":"120"}},
{"name":"DungeonDesigner","status":true,"description":"Help design a Dungeon","parameters":{"EnemyMap":"8"}},
{"name":"highDPIFix","status":true,"description":"NW.js acts wired under high-DPI screen and scale enabled.(Size is not right). This plugin trys to fix this bug.","parameters":{}},
{"name":"Animate","status":true,"description":"A helper script trys to make the implementation of animation effects more easily and painless.","parameters":{}},
{"name":"bezier","status":true,"description":"","parameters":{}},
{"name":"mustDo","status":true,"description":"Make sure some code must be done whether the bitmap is loaded or not.","parameters":{}}
];
