// Generated by CoffeeScript 1.8.0

/*:
@plugindesc skip the command choose fight or escape on battle.
@author IamI
 */

(function() {
  Scene_Battle._SkipPartyCommand_Alias_changeInputWindow = Scene_Battle.prototype.changeInputWindow;

  Scene_Battle.prototype.changeInputWindow = function() {
    if (BattleManager.isInputting()) {
      if (BattleManager.actor()) {
        return this.startActorCommandSelection();
      } else {
        return this.commandFight();
      }
    } else {
      return this.endCommandSelection();
    }
  };

}).call(this);
